security:
    providers:
        in_memory:
            memory:
                users:
                    anna:
                        password: $2y$12$Q/mboqufl.GGFeUtjwQ7uOZDWY9onBUOPm0cORKvTTckq6db86.Ji
                        roles: 'ROLE_USER'
                    admin:
                        password: 2y$12$xPRVp4N0qjD59G8TgWyPBeQNlAhwkGhM8Wr6p6my57g46gsxigz0O
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
    access_control:
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_USER] }